name: Build

on:
  pull_request:
    branches:
      - main
  workflow_call:
    secrets:
      MAP_API_KEY:
        description: 'A map key from the caller workflow'
        required: true

jobs:
  build:
    name: Run Build Code 🏗
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1

      - name: Set up JDK 🐘
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11

      - name: Update Username from Secrets
        run: echo mapApiKey="${{ secrets.MAP_API_KEY }}" > ./local.properties

      - name: Setup Gradle and Build Debug🐘
        uses: gradle/gradle-build-action@v2
        with:
          arguments: assembleDebug --stacktrace
          gradle-version: 7.5.1

      - name: Upload build output 📤
        if:  ${{ success() }}
        uses: actions/upload-artifact@v3
        with:
          name: build-output
          path: ${{github.workspace}}/app/build/outputs
          if-no-files-found: error